vscode:
  extensions:
    - bibhasdn.django-snippets@1.1.1:wx3yPyLjTwPZA2Oy+2ruaA==
    - bigonesystems.django@1.0.2:P/DthMuq/Semg3tL1M4yaw==
    - batisteo.vscode-django@0.19.0:GOHmg6fGCbzkKe2S73i7Ig==
    - tht13.python@0.2.3:1RPVn9AW+lkCOD6zUWqiIw==
    - ms-python.python@2019.10.44104:fKYRb8X8FA37fMd+hgvv2A==